### PR TITLE
Added Lists to the HTMLElements directory

### PR DESCRIPTION
**Pull request by oyakhilomee**
I added a List section to the HTMLElements directory and made notes on why it is important for SEO.

### CODE REVIEW

**Comment by PatricNox** [comment]
Hello!

Thank you so much for your contribution, this is one of the best ones so far!

feel free to contribute with more useful stuff here or visit https://github.com/fossbarrow for other repositories to contribute to!

Unfortunately, I cannot merge this at this state as there's unresolved merge conflicts. 
Please do fix them and push the commit, and I'll merge this PR!

**Comment by oyakhilomee** [comment]
@PatricNox would you please direct me on how I can resolve the conflict or go about finding where to resolve it.

Thanks and I'll definitely love to contribute more. Thanks for rejecting the first one 😄

**Comment by oyakhilomee** [comment]
why is it marking the header tag section? I didn't contribute that part.

**Comment by PatricNox** [comment]
Since the same lines.

**Comment by oyakhilomee** [comment]
I don't understand?

**Comment by PatricNox** [comment]
@oyakhilomee  Your added lines is conflicting with some lines that someone else have added just before your PR. 
You can solve the conflict by simply keeping both tracks. 

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by PatricNox** [comment]
Hello @oyakhilomee, I've fixed the merge conflict for you.

Thanks for your addition and remember to visit https://github.com/fossbarrow for other repositories to contribute to!

**Comment by oyakhilomee** [comment]
Thanks @PatricNox but I was wondering if you had the time to show me how you fixed the conflict if you don't mind? 

Can I dm you on Twitter?

**Comment by PatricNox** [comment]
@oyakhilomee  I used github's merge conflict handler, and simply kept all incoming changes whilst moving your addition to the end of file section. 

For practice, I recommend using an editor such as [VSCode](https://code.visualstudio.com/) since it will help you dramatically.

**Pull request merged**
