### PR TITLE
SEO Backlinks

### PR DESCRIPTION
**Pull request by oyakhilomee**
## Details about the addition 
Backlinks are links created on a page of a website to link to another page on another website usually because of the usefulness of the content to the users who would be clicking on that link.

### CODE REVIEW

**Comment by PatricNox** [comment]
Hello!

Could you please add a practical example to your addition? 

Thanks!

**Comment by oyakhilomee** [comment]
@PatricNox got it. Will do.

**Comment by oyakhilomee** [comment]
Hey @PatricNox, made the changes to the first message on this conversation thread. Is that ok?

**Comment by PatricNox** [comment]
No one will go into the Pull requests when reading up on SEO tips, put the example in the files with a new commit instead.

**Comment by oyakhilomee** [comment]
Okay, that makes sense.

**Comment by PatricNox** [comment]
@oyakhilomee  thank you for this additional PR, great work!

Just as before, feel free to checkout https://github.com/fossbarrow for more repositories to contribute to. :)

**Pull request merged**
