### PR TITLE
Added a meta refresh redirect

### PR DESCRIPTION
**Pull request by oyakhilomee**
Hello,

I added a meta-refresh-redirect to the README.MD file in the HTMLElements Directory.

Thank you.

### CODE REVIEW

**Comment by PatricNox** [comment]
Hello @oyakhilomee !

Thank you for your contribution! 

However, please add some information about why it's good for SEO to the readme.

Until then, I'll label this as invalid.

Thanks!

**Comment by oyakhilomee** [comment]
Ok I'll do that.

**Comment by PatricNox** [comment]
@oyakhilomee With your update, I'm still not convinced if it makes any good advantage for SEO purposes.

This blog claims it is bad overall:
https://benohead.com/blog/2013/02/18/http-redirect-meta-refresh-frame-javascript/

Whilst this stackoverflow post claims it to be OK for google analytics, but not recommended in SEO overall.
https://stackoverflow.com/questions/54599280/google-and-w3c-says-to-avoid-using-meta-refresh-what-to-do-instead-when-using-g

**Comment by oyakhilomee** [comment]
@PatricNox ok. If it's not good. We'll strike it out. I'll add another seo checklist. 

Thanks for following this up.

**Pull request closed without merging**
